apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc1
  namespace: alison
  labels:
    s1: p1
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: ibmc-block-gold
  resources:
    requests:
      storage: 2Gi
